from crewai import Agent, Crew, Process, Task
from crewai.project import CrewBase, agent, crew, task
from crewai.agents.agent_builder.base_agent import BaseAgent
from typing import Any, List
from ..utils.mcpUtils import McpUtils
from ..utils.llmUtils import getLlm, getVerbose
from enum import Enum
from pydantic import BaseModel, Field

class Intent(Enum):
    EMERGING_TECHNOLOGY_RESEARCH = "EMERGING_TECHNOLOGY_RESEARCH"
    EMERGING_TECHNOLOGY_FOLLOW_UP_QUERY = "EMERGING_TECHNOLOGY_FOLLOW_UP_QUERY"
    GENERAL_CHAT = "GENERAL_CHAT"

class OrchestratorWorkerAnswer(BaseModel):
   intent:Intent = Field(description="Intent of the Prompt")
   answer:str = Field(description="Report or answer as generated by the crew")

@CrewBase
class OrchestratorWorkerCrew():
    """OrchestratorWorkerCrew crew"""

    agents_config = '../config/orchestratorWorkerAgents.yaml'
    tasks_config = '../config/orchestratorWorkerTasks.yaml'
    agents: List[BaseAgent]
    tasks: List[Task]
    stepCallback:Any=None

    def __init__(self, stepCallback=None):
        self.stepCallback = stepCallback

    @agent
    def intent_analyst(self) -> Agent:
        return Agent(
            config=self.agents_config['intent_analyst'],
            verbose=getVerbose(),
            llm=getLlm()
        )

    @agent
    def researcher(self) -> Agent:
        return Agent(
            config=self.agents_config['researcher'],
            verbose=getVerbose(),
            tools=McpUtils().getTools(),
            llm=getLlm()
        )

    @agent
    def reporting_analyst(self) -> Agent:
        return Agent(
            config=self.agents_config['reporting_analyst'],
            verbose=getVerbose(),
            tools=McpUtils().getTools(),
            llm=getLlm()
        )

    @agent
    def followup_question_agent(self) -> Agent:
        return Agent(
            config=self.agents_config['followup_question_agent'],
            verbose=getVerbose(),
            llm=getLlm()
        )

    @agent
    def assistant(self) -> Agent:
        return Agent(
            config=self.agents_config['assistant'],
            verbose=getVerbose(),
            tools=McpUtils().getTools(),
            llm=getLlm()
        )

    @task
    def orchestrator_task(self) -> Task:
        return Task(
            config=self.tasks_config['orchestrator_task'],
            output_pydantic=OrchestratorWorkerAnswer
        )

    @crew
    def crew(self) -> Crew:
        """Creates the OrchestratorWorkerCrew crew"""
        return Crew(
            name="OrchestratorWorkerCrew",
            agents=self.agents,
            tasks=self.tasks,
            process=Process.hierarchical,
            manager_llm=getLlm(),
            verbose=getVerbose(),
            step_callback=self.stepCallback,
            task_callback=self.stepCallback,
            tracing=True
        )